from turtle import *
from time import sleep

t = Turtle()

#japão - fácil1
t.pu()
t.begin_fill()
t.fillcolor("white")
t.goto(-200,-100)
t.pd()
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()
t.pu()
t.goto(0,-20)
t.pd()
t.pencolor("red")
t.begin_fill()
t.fillcolor("red")
t.circle(70)
t.end_fill()

sleep(2)
t.clear()

#rússia - fácil2
t.pu()
t.begin_fill()
t.fillcolor("white")
t.goto(-200,-100)
t.pd()
t.pencolor("black")
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("blue")
t.goto(-200,100)
t.pd()
t.pencolor("blue")
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("red")
t.goto(-200,0)
t.pd()
t.pencolor("red")
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

sleep(2)
t.clear()

#islândia - médio1
t.pu()
t.begin_fill()
t.fillcolor("#120A8F")
t.goto(-200,-100)
t.pd()
t.pencolor("black")
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()

t.pu()
t.goto(-200,17)
t.begin_fill()
t.fillcolor("white")
t.pd()
t.pencolor("white")
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(70)
    t.lt(90)
t.end_fill()

t.pu()
t.goto(-186,-100)
t.begin_fill()
t.fillcolor("white")
t.pd()
t.forward(70)
t.lt(90)
t.fd(300)
t.rt(90)
t.forward(70)
t.rt(90)
t.fd(300)
t.rt(90)
t.end_fill()

t.pu()
t.goto(-200,31)
t.begin_fill()
t.fillcolor("red")
t.pd()
t.pencolor("red")
t.right(180)
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(40)
    t.lt(90)
t.end_fill()

t.pu()
t.goto(-142,-100)
t.begin_fill()
t.fillcolor("red")
t.pd()
t.forward(40)
t.lt(90)
t.fd(300)
t.rt(90)
t.forward(40)
t.rt(90)
t.fd(300)
t.rt(90)
t.end_fill()

sleep(2)
t.clear()

#niger - médio2
t.pu()
t.rt(180)
t.begin_fill()
t.fillcolor("orange")
t.goto(-200,-100)
t.pd()
t.pencolor("black")
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("white")
t.goto(-200,100)
t.pd()
t.pencolor("white")
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("green")
t.goto(-200,0)
t.pd()
t.pencolor("green")
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

t.pu()
t.goto(0,10)
t.pd()
t.pencolor("orange")
t.begin_fill()
t.fillcolor("orange")
t.circle(40)
t.end_fill()

sleep(2)
t.clear()


#bahamas - médio3
t.pu()
t.begin_fill()
t.fillcolor("#008B8B")
t.goto(-200,-100)
t.pd()
t.pencolor("black")
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("#FFD700")
t.goto(-200,100)
t.pd()
t.pencolor("#FFD700")
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

t.pu()
t.goto(-200,200)
t.begin_fill()
t.fillcolor("black")
t.pd()
t.pencolor("black")
t.right(45)
t.forward(215)
t.rt(90)
t.forward(215)
t.end_fill()

sleep(2)
t.clear()

#gambia - médio4
t.lt(135)
t.pu()
t.begin_fill()
t.fillcolor("red")
t.goto(-200,-100)
t.pd()
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("white")
t.goto(-200,100)
t.pd()
t.pencolor("white")
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("green")
t.goto(-200,0)
t.pd()
t.pencolor("green")
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

t.rt(180)
t.pu()
t.goto(-200,21)
t.begin_fill()
t.fillcolor("#120A8F")
t.pd()
t.pencolor("#120A8F")
t.right(180)
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(55)
    t.lt(90)
t.end_fill()

sleep(2)
t.clear()


#emirados árabes - médio5
t.pu()
t.begin_fill()
t.fillcolor("green")
t.goto(-200,-100)
t.pd()
t.pencolor("black")
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("white")
t.goto(-200,100)
t.pd()
t.pencolor("white")
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("black")
t.goto(-200,0)
t.pd()
t.pencolor("black")
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("red")
t.goto(-200,200)
t.pd()
t.pencolor("red")
t.fd(100)
t.right(90)
t.fd(300)
t.rt(90)
t.fd(100)
t.end_fill()

sleep(2)
t.clear()

#noruega - média6
t.pu()
t.right(180)
t.begin_fill()
t.fillcolor("red")
t.goto(-200,-100)
t.pd()
t.pencolor("black")
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()

t.pu()
t.goto(-200,17)
t.begin_fill()
t.fillcolor("white")
t.pd()
t.pencolor("white")
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(70)
    t.lt(90)
t.end_fill()

t.pu()
t.goto(-186,-100)
t.begin_fill()
t.fillcolor("white")
t.pd()
t.forward(70)
t.lt(90)
t.fd(300)
t.rt(90)
t.forward(70)
t.rt(90)
t.fd(300)
t.rt(90)
t.end_fill()

t.pu()
t.goto(-200,31)
t.begin_fill()
t.fillcolor("#120A8F")
t.pd()
t.pencolor("#120A8F")
t.right(180)
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(40)
    t.lt(90)
t.end_fill()

t.pu()
t.goto(-142,-100)
t.begin_fill()
t.fillcolor("#120A8F")
t.pd()
t.forward(40)
t.lt(90)
t.fd(300)
t.rt(90)
t.forward(40)
t.rt(90)
t.fd(300)
t.rt(90)
t.end_fill()

sleep(2)
t.clear()

# grécia - difícil1
t.pu()
t.right(180)
t.begin_fill()
t.fillcolor("white")
t.goto(-200,-100)
t.pd()
t.pencolor("black")
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()

t.pu()
t.goto(-200,200)
t.pd()
t.pencolor("#0F2284")
for _ in range(4):
    t.begin_fill()
    t.fillcolor("#0F2284")
    for _ in range (2):
        t.fd(400)
        t.rt(90)
        t.fd(33)
        t.rt(90)
    t.end_fill()
    t.rt(90)
    t.fd(66)
    t.lt(90)
t.begin_fill()
t.fillcolor("#0F2284")
for _ in range (2):
    t.fd(400)
    t.rt(90)
    t.fd(36)
    t.rt(90)
t.end_fill()

t.pu()
t.goto(-200,200)
t.pd()
t.begin_fill()
t.fillcolor("#0F2284")
for _ in range (4):
    t.fd(165)
    t.rt(90)
t.end_fill()

t.pu()
t.goto(-134,200)
t.begin_fill()
t.fillcolor("white")
t.pd()
t.pencolor("white")
for _ in range(2):
    t.forward(33)
    t.rt(90)
    t.fd(165)
    t.rt(90)
t.end_fill()
t.pu()
t.goto(-200,134)
t.begin_fill()
t.fillcolor("white")
t.pd()
for _ in range(2):
    t.forward(165)
    t.rt(90)
    t.fd(33)
    t.rt(90)
t.end_fill()

sleep(2)
t.clear()

#são tomé e príncipe - difícil2
t.pu()
t.begin_fill()
t.fillcolor("green")
t.goto(-200,-100)
t.pd()
t.pencolor("black")
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("yellow")
t.goto(-200,100)
t.pd()
t.pencolor("yellow")
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

t.pu()
t.goto(-200,200)
t.begin_fill()
t.fillcolor("red")
t.pd()
t.pencolor("red")
t.right(45)
t.forward(215)
t.rt(90)
t.forward(215)
t.end_fill()

t.pu()
t.lt(135)
t.goto(10,60)
t.pd()
t.pencolor("black")
t.begin_fill()
t.fillcolor("black")
for _ in range(5):
    t.fd(20)
    t.lt(72)
    t.fd(20)
    t.rt(144)
t.end_fill()

t.pu()
t.goto(100,60)
t.pd()
t.begin_fill()
t.fillcolor("black")
for _ in range(5):
    t.fd(20)
    t.lt(72)
    t.fd(20)
    t.rt(144)
t.end_fill()

sleep(2)
t.clear()


mainloop()