from turtle import *
from time import sleep

t = Turtle()

# #japão - fácil
# t.pu()
# t.begin_fill()
# t.fillcolor("white")
# t.goto(-200,-100)
# t.pd()
# for _ in range (2):
#     t.forward(400)
#     t.left(90)
#     t.fd(300)
#     t.lt(90)
# t.end_fill()
# t.pu()
# t.goto(0,-20)
# t.pd()
# t.begin_fill()
# t.fillcolor("red")
# t.circle(70)
# t.end_fill()

# sleep(1)
# t.clear()

# #rússia - fácil
# t.pu()
# t.begin_fill()
# t.fillcolor("white")
# t.goto(-200,-100)
# t.pd()
# for _ in range (2):
#     t.forward(400)
#     t.left(90)
#     t.fd(300)
#     t.lt(90)
# t.end_fill()

# t.pu()
# t.begin_fill()
# t.fillcolor("blue")
# t.goto(-200,100)
# t.pd()
# for _ in range (2):
#     t.fd(400)
#     t.right(90)
#     t.fd(100)
#     t.right(90)
# t.end_fill()

# t.pu()
# t.begin_fill()
# t.fillcolor("red")
# t.goto(-200,0)
# t.pd()
# for _ in range (2):
#     t.fd(400)
#     t.right(90)
#     t.fd(100)
#     t.right(90)
# t.end_fill()

# sleep(1)
# t.clear()

# #islândia - médio
# t.pu()
# t.begin_fill()
# t.fillcolor("#120A8F")
# t.goto(-200,-100)
# t.pd()
# for _ in range (2):
#     t.forward(400)
#     t.left(90)
#     t.fd(300)
#     t.lt(90)
# t.end_fill()

# t.pu()
# t.goto(-200,17)
# t.begin_fill()
# t.fillcolor("white")
# t.pd()
# for _ in range (2):
#     t.forward(400)
#     t.left(90)
#     t.fd(70)
#     t.lt(90)
# t.end_fill()

# t.pu()
# t.goto(-186,-100)
# t.begin_fill()
# t.fillcolor("white")
# t.pd()
# t.forward(70)
# t.lt(90)
# t.fd(300)
# t.rt(90)
# t.forward(70)
# t.rt(90)
# t.fd(300)
# t.rt(90)
# t.end_fill()

# t.pu()
# t.goto(-200,31)
# t.begin_fill()
# t.fillcolor("red")
# t.pd()
# t.right(180)
# for _ in range (2):
#     t.forward(400)
#     t.left(90)
#     t.fd(40)
#     t.lt(90)
# t.end_fill()

# t.pu()
# t.goto(-142,-100)
# t.begin_fill()
# t.fillcolor("red")
# t.pd()
# t.forward(40)
# t.lt(90)
# t.fd(300)
# t.rt(90)
# t.forward(40)
# t.rt(90)
# t.fd(300)
# t.rt(90)
# t.end_fill()

# sleep(1)
# t.clear()

# #niger - médio
# t.pu()
# t.begin_fill()
# t.fillcolor("orange")
# t.goto(-200,-100)
# t.pd()
# for _ in range (2):
#     t.forward(400)
#     t.left(90)
#     t.fd(300)
#     t.lt(90)
# t.end_fill()

# t.pu()
# t.begin_fill()
# t.fillcolor("white")
# t.goto(-200,100)
# t.pd()
# for _ in range (2):
#     t.fd(400)
#     t.right(90)
#     t.fd(100)
#     t.right(90)
# t.end_fill()

# t.pu()
# t.begin_fill()
# t.fillcolor("green")
# t.goto(-200,0)
# t.pd()
# for _ in range (2):
#     t.fd(400)
#     t.right(90)
#     t.fd(100)
#     t.right(90)
# t.end_fill()

# t.pu()
# t.goto(0,10)
# t.pd()
# t.begin_fill()
# t.fillcolor("orange")
# t.circle(40)
# t.end_fill()

# sleep(1)
# t.clear()


# #bahamas - médio
# t.pu()
# t.begin_fill()
# t.fillcolor("#008B8B")
# t.goto(-200,-100)
# t.pd()
# for _ in range (2):
#     t.forward(400)
#     t.left(90)
#     t.fd(300)
#     t.lt(90)
# t.end_fill()

# t.pu()
# t.begin_fill()
# t.fillcolor("#FFD700")
# t.goto(-200,100)
# t.pd()
# for _ in range (2):
#     t.fd(400)
#     t.right(90)
#     t.fd(100)
#     t.right(90)
# t.end_fill()

# t.pu()
# t.goto(-200,200)
# t.begin_fill()
# t.fillcolor("black")
# t.pd()
# t.right(45)
# t.forward(215)
# t.rt(90)
# t.forward(215)
# t.end_fill()

# sleep(1)
# t.clear()

# #gambia - médio
# t.pu()
# t.begin_fill()
# t.fillcolor("red")
# t.goto(-200,-100)
# t.pd()
# for _ in range (2):
#     t.forward(400)
#     t.left(90)
#     t.fd(300)
#     t.lt(90)
# t.end_fill()

# t.pu()
# t.begin_fill()
# t.fillcolor("white")
# t.goto(-200,100)
# t.pd()
# for _ in range (2):
#     t.fd(400)
#     t.right(90)
#     t.fd(100)
#     t.right(90)
# t.end_fill()

# t.pu()
# t.begin_fill()
# t.fillcolor("green")
# t.goto(-200,0)
# t.pd()
# for _ in range (2):
#     t.fd(400)
#     t.right(90)
#     t.fd(100)
#     t.right(90)
# t.end_fill()

# t.rt(180)
# t.pu()
# t.goto(-200,21)
# t.begin_fill()
# t.fillcolor("#120A8F")
# t.pd()
# t.right(180)
# for _ in range (2):
#     t.forward(400)
#     t.left(90)
#     t.fd(55)
#     t.lt(90)
# t.end_fill()

# sleep(1)
# t.clear()


#emirados árabes - médio
t.pu()
t.begin_fill()
t.fillcolor("green")
t.goto(-200,-100)
t.pd()
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("white")
t.goto(-200,100)
t.pd()
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("black")
t.goto(-200,0)
t.pd()
for _ in range (2):
    t.fd(400)
    t.right(90)
    t.fd(100)
    t.right(90)
t.end_fill()

t.pu()
t.begin_fill()
t.fillcolor("red")
t.goto(-200,200)
t.pd()
t.fd(100)
t.right(90)
t.fd(300)
t.rt(90)
t.fd(100)
t.end_fill()

sleep(1)
t.clear()

#noruega - média
t.pu()
t.right(180)
t.begin_fill()
t.fillcolor("red")
t.goto(-200,-100)
t.pd()
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(300)
    t.lt(90)
t.end_fill()

t.pu()
t.goto(-200,17)
t.begin_fill()
t.fillcolor("white")
t.pd()
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(70)
    t.lt(90)
t.end_fill()

t.pu()
t.goto(-186,-100)
t.begin_fill()
t.fillcolor("white")
t.pd()
t.forward(70)
t.lt(90)
t.fd(300)
t.rt(90)
t.forward(70)
t.rt(90)
t.fd(300)
t.rt(90)
t.end_fill()

t.pu()
t.goto(-200,31)
t.begin_fill()
t.fillcolor("#120A8F")
t.pd()
t.right(180)
for _ in range (2):
    t.forward(400)
    t.left(90)
    t.fd(40)
    t.lt(90)
t.end_fill()

t.pu()
t.goto(-142,-100)
t.begin_fill()
t.fillcolor("#120A8F")
t.pd()
t.forward(40)
t.lt(90)
t.fd(300)
t.rt(90)
t.forward(40)
t.rt(90)
t.fd(300)
t.rt(90)
t.end_fill()

sleep(1)
t.clear()

mainloop()